name: okio
description: Okio into dart.
version: 0.5.0
author: clay <clay@mojo.run>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  path: ^1.4.1
  rxdart: ^0.19.0
  rx_command: ^4.0.1
  http: ^0.12.0
  http2: ^0.1.8+2
  protobuf: ^0.10.4
  googleapis_auth: ^0.2.5+3

dev_dependencies:
  test: ^1.0.0
